kyverno/kyverno-json

.github/workflows/ah-lint.yaml, .github/workflows/check-actions.yaml, .github/workflows/codegen.yaml, .github/workflows/ct-lint.yaml, .github/workflows/helm-install.yaml, .github/workflows/helm-release.yaml, .github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml
Update workflow permissions.
Fixes #26
=> chore: update workflow permissions

.github/workflows/deploy.yaml
=> feat: add docs deployment workflow

.github/workflows/tests.yaml, .gitignore, Makefile
=> chore: upload code coverage

.release-notes/_template.md, .release-notes/main.md, .release-notes/v0.0.1.md
=> release: v0.0.1

website/docs/install.md
=> fix: install docs

.github/workflows/codeql.yaml
Add schema in codeql workflow.
=> chore: add schema in codeql workflow

pkg/version/version.go, pkg/version/version_test.go
Add version package unit tests.
=> chore: add version package unit tests

pkg/utils/reflect/match.go
=> fix: match scalar

.github/workflows/codeql.yaml
=> fix: codeql workflow

.github/workflows/action.yml
=> fix: action test workflow

go.mod, go.sum, pkg/engine/template/template.go
=> chore: bump jmespath lib

pkg/apis/v1alpha1/any_test.go
=> chore: add a few unit tests

pkg/engine/assert/assert.go, pkg/engine/assert/match.go
Remove error prone validate func.
=> chore: remove error prone validate func

pkg/engine/assert/assert.go, pkg/engine/assert/assertion.go, pkg/engine/assert/match.go, pkg/engine/assert/parse.go, pkg/engine/assert/project.go, pkg/engine/template/options.go, pkg/engine/template/template.go
Add template options to improve extensibility.
=> feat: add template options

.goreleaser.yaml
Add brew tap release.
Fixes #235
=> feat: add brew tap release

website/docs/quick-start.md
The quick start policy is using the old policy format.
=> fix: update outdated quickstart policy in readme

.release-notes/main.md, pkg/policy/load.go, website/docs/policies/asserts.md
=> chore: small updates

website/docs/install.md
=> chore: update docs

.release-notes/_template.md, .release-notes/main.md, .release-notes/v0.0.2.md
=> release: v0.0.2

pkg/commands/scan/options.go
=> fix: json output

website/docs/overrides/main.html
=> feat: add website outdated banner

go.mod, go.sum
=> fix: bump jp lib

.github/workflows/tests.yaml, go.mod
=> chore: bump codecov

.github/dependabot.yml
Allow dependabot rebasing PRs.
=> chore: allow dependabot rebasing PRs

pkg/engine/mutate/parse.go
=> fix: map mutation

pkg/engine/mutate/parse.go
=> feat: simplify mutations

pkg/engine/mutate/parse.go
Fix mutation trees value propagation.
=> fix: mutations trees value propagation

pkg/engine/template/template.go
Fix concurrency issue when parsing expression.
=> fix: concurrency issue when parsing expression

pkg/matching/match.go
=> fix: linter

.github/workflows/tests.yaml
=> fix: decouple upload to codecov

.github/workflows/ah-lint.yaml, .github/workflows/check-actions.yaml, .github/workflows/codegen.yaml, .github/workflows/ct-lint.yaml, .github/workflows/helm-install.yaml, .github/workflows/lint.yaml
Fix workflow names for branch protection.
=> fix: workflow names for branch protection

.gitignore
=> chore: add dist gitignore

.gitignore, Makefile, requirements.txt
=> fix: use python virtual env

pkg/engine/assert/parse.go
Improve field not found message.
=> chore: improve field not found message

pkg/apis/policy/v1alpha1/any.go, pkg/apis/policy/v1alpha1/any_test.go, pkg/engine/template/functions/json_parse.go, pkg/engine/template/kyverno/functions.go, pkg/payload/load.go
=> fix: use k8s json lib

pkg/engine/assert/assert_test.go, pkg/engine/assert/expression.go, pkg/engine/assert/parse.go, pkg/engine/assert/project.go, pkg/engine/assert/project_test.go, pkg/engine/template/options.go, pkg/engine/template/template.go, pkg/matching/match.go
=> feat: reuse compiled expressions

pkg/apis/policy/v1alpha1/validating_policy.go
=> fix: remove yaml markers

Makefile, pkg/apis/policy/v1alpha1/any.go, pkg/apis/policy/v1alpha1/assertion.go, pkg/apis/policy/v1alpha1/assertion_tree.go, pkg/apis/policy/v1alpha1/deep_copy.go, pkg/engine/assert/assert_test.go, pkg/engine/assert/parse.go, pkg/matching/match.go, pkg/policy/load_test.go, website/apis/config.yaml
Hold compiled assertion in api.
=> feat: hold compiled assertion in api

pkg/apis/policy/v1alpha1/assertion.go, pkg/apis/policy/v1alpha1/engine.go, pkg/apis/policy/v1alpha1/validating_policy_spec.go, pkg/apis/policy/v1alpha1/validating_rule.go, website/docs/apis/kyverno-json.v1alpha1.md
=> fix: engine api

pkg/apis/policy/v1alpha1/assertion_tree.go, pkg/utils/hash/hash.go
=> refactor: move hash in utils

pkg/apis/policy/v1alpha1/any.go, pkg/apis/policy/v1alpha1/assertion_tree.go, pkg/utils/copy/deep_copy.go
=> feat: export deep copy utils
