.github/workflows/check-actions.yaml

Bump github-actions-ensure-sha-pinned-actions.

chore: bump github-actions-ensure-sha-pinned-actions

---

pkg/engine/assert/expression_test.go
pkg/engine/assert/project.go
pkg/engine/assert/project_test.go

Index not found when projecting should not trigger error.

fix: index not found should not trigger error

---

pkg/engine/assert/parse.go

fix: slice check with null value

---

.docs/RELEASE.md
.github/workflows/docs-main.yaml
.github/workflows/docs-release.yaml
.release-notes/_template.md
.release-notes/main.md
Makefile
website/mkdocs.base.yaml

Add versioned docs support.
Fixes #223

feat: add versioned docs support

---

.github/actions/install/README.md
.github/actions/install/action.yml
.github/workflows/action.yml

chore: add github action

---

pkg/commands/scan/command.go
pkg/commands/scan/options.go
pkg/commands/scan/output.go
website/docs/cli/commands/kyverno-json_scan.md

feat: add json output support

---

pkg/engine/assert/assert.go
pkg/engine/assert/assertion.go
pkg/engine/assert/binding.go
pkg/engine/assert/expression.go
pkg/engine/assert/match.go
pkg/engine/assert/parse.go
pkg/engine/assert/project.go
pkg/engine/assert/project_test.go
pkg/engine/match/match.go
pkg/engine/template/binding.go
pkg/engine/template/functions/at.go
pkg/engine/template/functions/concat.go
pkg/engine/template/functions/json_parse.go
pkg/engine/template/functions/wildcard.go
pkg/engine/template/kyverno/arithmetic.go
pkg/engine/template/kyverno/arithmetic_test.go
pkg/engine/template/kyverno/error.go
pkg/engine/template/kyverno/functions.go
pkg/engine/template/kyverno/functions_test.go
pkg/engine/template/kyverno/time.go
pkg/engine/template/kyverno/time_test.go
pkg/engine/template/kyverno/utils.go
pkg/engine/template/template.go

chore: use any instead of interface

---

pkg/binding/binding.go
pkg/engine/assert/assert.go
pkg/engine/assert/binding.go
pkg/json-engine/engine.go
pkg/matching/match.go

Remove deps from engine to api.
Fixes #18

fix: remove deps from engine to api

---

pkg/commands/scan/options.go
pkg/json-engine/engine.go
pkg/server/model/response.go
test/api/go/main/main.go

Refactor violations and error in rule response.

refactor: violations and error in rule response

---

pkg/engine/mutate/expression.go
pkg/engine/mutate/mutate.go
pkg/engine/mutate/mutation.go
pkg/engine/mutate/parse.go
pkg/engine/mutate/project.go

Add initial support for mutation trees.

feat: add initial support for mutation trees

---

pkg/commands/scan/options.go
pkg/json-engine/engine.go
pkg/matching/match.go
pkg/server/model/response.go
test/api/go/main/main.go

Violations were not visible in json output because errors are parsed as `{}`. This PR converts violation from array of errors to array of strings, Violations are now visible.
Current behaviour:
```
"Rules": [
{
"Rule": {
"name": "detect-untrusted-flag",
"match": {
"any": [
{
"(Stages[].Commands[?Name=='RUN'].CmdLine[][] | length(@) \u003e `0`)": true
}
]
},
"assert": {
"any": [
{
"message": "Dockerfile contains the '--allow-untrusted' which is not preferred",
"check": {
"~.(Stages[].Commands[?Name=='RUN'].CmdLine[][])": {
"(contains(@, '--allow-untrusted') \u0026\u0026 (contains(@, 'apk')))": false
}
}
}
]
}
},
"Identifier": "",
"Error": null,
"Violations": [
{}
]
}
]
}
]
}
```
Updated behaviour:
```bash
❯ ./../../../../kyverno-json scan --policy ./policy.yaml --payload ./payload.json …
```

fix: violation not visible in json output

---

pkg/commands/scan/report.go

fix(reports): rename badValue to value

---

pkg/engine/assert/expression.go
pkg/engine/assert/parse.go
pkg/engine/assert/project.go
pkg/engine/assert/project_test.go

Fix projecting over inexistent fields.

fix: projecting over inexistent fields

---

pkg/engine/assert/project.go
pkg/engine/assert/project_test.go

fix: nil value in projection

---

.github/workflows/pr-semantics.yaml

chore: add semantics pr check

---

.github/workflows/tests.yaml

Remove checkout from upload to codecov.

chore: remove checkout from upload to codecov

---

pkg/apis/policy/v1alpha1/any.go
pkg/apis/policy/v1alpha1/any_test.go

fix: deep copy Any objects

---

pkg/apis/policy/v1alpha1/validating_rule.go
pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
pkg/matching/match.go
pkg/policy/load_test.go

Assert in api should not be a pointer.

fix: assert in api should not be a pointer

---

pkg/commands/jp/query/command.go
pkg/commands/scan/options.go
pkg/engine/assert/binding.go
pkg/engine/assert/project.go
pkg/engine/template/template.go
pkg/json-engine/engine.go
pkg/server/playground/handler.go
pkg/server/scan/handler.go

refactor: rename Execute to ExecuteJP

---

pkg/syntax/expression/expression.go

fix: use ; as engine separator

---

pkg/core/assertion/assertion.go
pkg/core/matching/equal.go
pkg/core/matching/match.go
pkg/core/matching/number.go
pkg/core/matching/number_test.go

Introduce matching package in core.

refactor: introduce matching package in core

---

go.mod
go.sum
pkg/apis/policy/v1alpha1/assertion_tree.go
pkg/json-engine/engine.go
pkg/matching/compiler.go
pkg/matching/match.go
website/apis/config.yaml

Add assertion compiler (with caching).

feat: add assertion compiler

---

go.mod
go.sum
pkg/matching/compiler.go

chore: bump xxhash

---

pkg/commands/jp/query/command.go
pkg/commands/scan/options.go
pkg/core/assertion/assertion.go
pkg/core/assertion/assertion_test.go
pkg/core/compilers/cel/cel.go
pkg/core/compilers/compilers.go
pkg/core/compilers/execute.go
pkg/core/compilers/jp/jp.go
pkg/core/compilers/program.go
pkg/core/projection/projection.go
pkg/core/projection/projection_test.go
pkg/json-engine/engine.go
pkg/matching/compiler.go
pkg/server/playground/handler.go
pkg/server/scan/handler.go

feat: improve compilers package

---

pkg/json-engine/engine.go
pkg/matching/compiler.go
pkg/matching/match.go

fix: assertion compiler cache

---

pkg/core/assertion/assertion.go

refactor: assertion parsing

---

pkg/core/assertion/assertion.go
pkg/core/assertion/assertion_test.go

Add path to assertion parsing.

fix: add path to assertion parsing

---

pkg/apis/policy/v1alpha1/any.go
pkg/apis/policy/v1alpha1/assertion_tree.go
pkg/core/assertion/assertion.go
pkg/core/assertion/assertion_test.go
pkg/core/projection/projection.go
pkg/core/projection/projection_test.go
pkg/json-engine/compiler.go

Implement compile time path propagation.

feat: implement compile time path propagation

---

pkg/apis/policy/v1alpha1/assertion_tree.go

fix: add missing deepcopy func

---

pkg/apis/policy/v1alpha1/any.go
pkg/apis/policy/v1alpha1/assertion_tree.go

Add IsNil to Any and AssertionTree.

feat: add IsNil to Any and AssertionTree
